baseURL = 'https://lmorillas.github.io/como-uso-learner-labs'
#baseURL = '/'
languageCode = 'es-es'
title = 'Cómo uso Learner Labs en el Aula'

publishDir = 'docs'

theme = ["github.com/dzello/reveal-hugo"]


[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "white"